# Generated by Django 6.0.6 on 2026-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=10000),
        ),
    ]
