# Generated by Django 6.0.6 on 2026-06-19 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='join_pots', to=settings.AUTH_USER_MODEL),
        ),
    ]
